[package]
name = "verify-td-quote"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
attestation-service = { path = "../../attestation-service", features = ["tdx-verifier"] }
anyhow.workspace = true
